### ISSUE TITLE
Downloading dotnet-install error

### ISSUE THREAD

**Issue by wdpfm** [RestoreMonarchy/pterodactyl-valheim-umod#1]
Downloading dotnet-install...
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.405/dotnet-sdk-3.1.405-linux-x64.tar.gz
curl: (23) Failed writing body (0 != 16372)
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.405/dotnet-sdk-3.1.405-linux-x64.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.1.405
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Comment by RestoreMonarchy** [comment]
Yeah I've got the same error and I'm trying to resolve it
